### ISSUE TITLE
Convert Numeric type to Integer failed

### ISSUE THREAD

**Issue by WhatAKitty** [Dreamroute/excel-helper#2]
The cell that has features:
* Number value [ 12 ]
* cell type is Numeric

caused the error:  For input string: "12.0"

Why not parse int like bellow 
```java
value = new BigDecimal(cv).intValue();
```
instead of like that
```java
value = Integer.valueOf(new BigDecimal(cv).toPlainString());
```

**Comment by Dreamroute** [comment]
@WhatAKitty 用toPlainString()这个方法是避免默认出现科学计数法，至于你说的这个错误我没办法复现，你看看com.mook.excel.helper.HelperTest.baseTest()这个方法里面有没有把你的这种场景覆盖到呢？如果没有麻烦提醒我一下。

**Comment by WhatAKitty** [comment]
@Dreamroute 
环境：
* 系统： Windows 10
* Excel识别错误列值：数字12
* Excel-helper版本：latest
问题：
* 12会被识别为12.0

**Comment by WhatAKitty** [comment]
@Dreamroute BaseTest里面的测试需要将excel文件放入test/resource；建议不要直接使用本地路径。

**Comment by Dreamroute** [comment]
@WhatAKitty 1.String类型那个pr已经合并了；2.把测试文件从本地挪到test/resources下面，这个IDE不同，平台不同、设置不同，很有可能获取的路径表现有点不太一样，所以先暂时就这样；

**Comment by WhatAKitty** [comment]
@Dreamroute 可以参照Spring的ClassPathResource的实现
